sudo: false

language: node_js

env:
  global:
    - DEBUG=electron-builder
  matrix:
  - TEST=lint-ci
  - TEST=test-ci

node_js:
  - node
  - 8

os:
  - linux
  - osx

cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    - flow-typed
    - app/node_modules

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso

install:
  - yarn
  - cd app && yarn && cd ..
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - "travis_wait 30 yarn $TEST"
