sudo: false

language: node_js

env:
  global:
    - DEBUG=electron-builder

os:
  - linux
  - osx

node_js:
  - node
  - 8

cache:
  apt: true
  yarn: true
  directories:
    - "$HOME/.npm"
    - node_modules
    - flow-typed
    - app/node_modules

addons:
  apt:
    packages:
      - xvfb

install:
  - yarn --ignore-scripts
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
    fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - yarn lint-ci && yarn build && yarn test-ci

after_success:
  - npm run coveralls

jobs:
  include:
    - stage: deploy
      name: Deploy to Github
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script: yarn build && yarn release
        on:
          branch: master

    - os: osx
      name: Deploy to Github
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script: yarn build && yarn release
        on:
          branch: master
