os: unstable

environment:
  DEBUG: electron-builder
  matrix:
    - nodejs_version: STABLE
      publish_build: true
    - nodejs_version: LTS

cache:
  - '%APPDATA%\npm-cache'
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

platform:
 - x86
 - x64

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn

test_script:
  - yarn lint-ci
  - yarn build
  - yarn test-ci

deploy_script:
- if not defined APPVEYOR_PULL_REQUEST_NUMBER if %APPVEYOR_REPO_BRANCH%==master if defined $env:publish_build yarn release
